enabled_layouts splits:split_axis=horizontal
background_image /home/zach/Pictures/bgs/teto.jpg
background_image_layout scaled
background_tint 0.95
font_size 12
bold_font auto
enable_ligatures always
map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right
map alt+shift+j launch --location=hsplit
map alt+shift+l launch --location=vsplit
map ctrl+alt+h resize_window narrower
map ctrl+alt+l resize_window wider
map ctrl+alt+j resize_window shorter
map ctrl+alt+k resize_window taller
