[main]
font=JetBrainsMono Nerd Font:size=16
pad=10x10

[colors-dark]
alpha=0.97

[colors-light]
alpha=0.97

[cursor]
style=block
blink=yes
blink-rate=500

[key-bindings]
prompt-prev=Control+Shift+z Control+k
prompt-next=Control+Shift+x Control+j

# rebind shift+enter to also trigger alt+pagedown
# i have something else bound in my nvim config so tmux works properly
[text-bindings]
\x1b\x1b[6~ = Shift+Return
