$terminal = footclient
$fileManager = thunar
$menu = fuzzel
$browser = librewolf
$bar = waybar
$discord = vesktop

$wallpaper_daemon = awww-daemon
$wallpaper = awww restore

$notification_daemon = swaync

$task_manager = missioncenter
$silent_steam = steam -silent
